services:
  app:
    image: donghub/account_app:latest
    container_name: account-app
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      DB_HOST: ${AWS_DB_HOST}
      DB_NAME: ${AWS_DB_NAME}
      DB_USER: ${AWS_DB_USER}
      DB_PASSWORD: ${AWS_DB_PASSWORD}
    restart: unless-stopped
